<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Application_Name</name>
   <tag></tag>
   <elementGuidId>2b534b28-0ff3-420c-ac5a-acc22f70b8e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__tile24-title-inner' and (text() = 'Manage Workorder' or . = 'Manage Workorder')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(text() = '${App_Name}')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__tile24-title-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a3c792da-5724-4897-8275-8b6c1f89457a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__tile24-title-inner</value>
      <webElementGuid>940cf9a6-a5fa-442d-a366-93000a43c43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTextLineClamp sapMTextMaxLine</value>
      <webElementGuid>0864e407-2cd0-49f5-9015-366e94c16264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Workorder</value>
      <webElementGuid>953c88b9-1832-4b91-879e-755521d22ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__tile24-title-inner&quot;)</value>
      <webElementGuid>8ce275e7-abee-453d-a0e4-410c50ffe825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__tile24-title-inner']</value>
      <webElementGuid>f3dc8e19-b781-4183-9a65-bacd9a76e7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__tile24-title']/span</value>
      <webElementGuid>6261861e-0e94-4080-ab43-bc98aaac8567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PM360'])[3]/following::span[3]</value>
      <webElementGuid>25a446dd-14b1-4768-90e1-f3dbb81eeae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Notification'])[1]/following::span[3]</value>
      <webElementGuid>8f679a45-f048-481b-a082-51d1cfeb4fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PM360'])[4]/preceding::span[1]</value>
      <webElementGuid>d819c4e3-c038-4ac1-9663-6f1bb8d773a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Sheet'])[2]/preceding::span[2]</value>
      <webElementGuid>9e54551b-ac55-4867-b162-1679c8553956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Workorder']/parent::*</value>
      <webElementGuid>d3932bc7-3fa6-4774-a5ba-c1b831d16e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/ul/li[2]/div/a/div/div/div/div/span/span</value>
      <webElementGuid>0dc0cf7a-4848-48fb-a858-88c6afe5ee04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__tile24-title-inner' and (text() = 'Manage Workorder' or . = 'Manage Workorder')]</value>
      <webElementGuid>dd761570-4942-4f4b-8e23-34343b5157ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
