<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Application_Title</name>
   <tag></tag>
   <elementGuidId>c2b68747-3ab9-4bd8-b230-a8338c2c2581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[text()='${AppName}'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'application-zpm360_managewo-manage-component---Master--smartFilterBar-filterItem-___INTERNAL_-Plants-bdi' and (text() = 'Maintenance Plant' or . = 'Maintenance Plant')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpm360_managewo-manage-component---Master--smartFilterBar-filterItem-___INTERNAL_-Plants-bdi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>e471a3b5-fc0a-4aef-8e29-c57b4fc914e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--smartFilterBar-filterItem-___INTERNAL_-Plants-bdi</value>
      <webElementGuid>81dfeef3-fb77-4b54-9c23-680445fffcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maintenance Plant</value>
      <webElementGuid>1917a78c-9f50-4b04-a797-72f221285a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpm360_managewo-manage-component---Master--smartFilterBar-filterItem-___INTERNAL_-Plants-bdi&quot;)</value>
      <webElementGuid>c6f2e7cd-e98e-41aa-9a6f-877f7c1d7519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-zpm360_managewo-manage-component---Master--smartFilterBar-filterItem-___INTERNAL_-Plants-bdi']</value>
      <webElementGuid>587dc1ff-4b5d-4163-a331-8fd8a78a584e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='application-zpm360_managewo-manage-component---Master--smartFilterBar-filterItem-___INTERNAL_-Plants']/bdi</value>
      <webElementGuid>7e45efb5-4d30-484d-84ff-3e8d4b308ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Work Order'])[1]/following::bdi[2]</value>
      <webElementGuid>8eeda428-b6b0-4745-8db9-cec0cd5aca2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[14]/following::bdi[2]</value>
      <webElementGuid>27e584c8-73f7-4516-b462-aa0d6896f62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Work Center'])[1]/preceding::bdi[1]</value>
      <webElementGuid>eab1e9ea-d8cc-406e-8b55-8940a98a6ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Person Responsible'])[1]/preceding::bdi[2]</value>
      <webElementGuid>eb723324-0549-4abf-92e7-89122cab4cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maintenance Plant']/parent::*</value>
      <webElementGuid>e77b00e0-666b-46b6-ba8e-a68a46312ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/bdi</value>
      <webElementGuid>4d8e303a-5301-4fe5-b63a-6caee90ad78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-zpm360_managewo-manage-component---Master--smartFilterBar-filterItem-___INTERNAL_-Plants-bdi' and (text() = 'Maintenance Plant' or . = 'Maintenance Plant')]</value>
      <webElementGuid>9655d4dc-45ff-4406-89e5-29af67e09c52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
