<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date_Text_Box</name>
   <tag></tag>
   <elementGuidId>98009ffb-783c-4ed6-ac50-2644550f4ad3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'search' and @id = 'application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I' and @placeholder = 'Search']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@placeholder = 'MM.dd.yyyy'])[${index}]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>667292cd-7560-4bce-a74a-c2e9d91f2f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>913fcd94-f46b-46ca-9fa6-b834e4346a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4b54ea6-8c7f-4cac-b45d-a02fb20f733f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I</value>
      <webElementGuid>c2113f03-3337-4500-a9eb-c1da2021df9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSFI</value>
      <webElementGuid>0eca62dc-0f7f-487f-8b8e-13a213b761b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ccfe1f62-226b-4d45-8f66-1a3227dbbc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I-labelledby</value>
      <webElementGuid>e73e26ca-5717-465e-9669-2fc7c8d59d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I&quot;)</value>
      <webElementGuid>8c1ae327-d173-416a-b07a-40b623b195e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I']</value>
      <webElementGuid>62503ea0-4bb3-44bb-a52a-3fbc976684de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-F']/input</value>
      <webElementGuid>77d540bb-eda3-46bf-979f-5942138e14f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7f89c10a-f249-4cd7-ae8f-ca4c2bd6c099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I' and @placeholder = 'Search']</value>
      <webElementGuid>8d7a0add-8c2c-40f9-95c4-02778740a111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
