<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Display_Input_Box</name>
   <tag></tag>
   <elementGuidId>732de07e-b71e-431b-af70-b25b31b68832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'search' and @id = 'application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I' and @placeholder = 'Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@placeholder,'${FieldValue}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b10a1394-c893-4740-9300-642c164bafd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>4785b99b-ef7b-4408-88da-64b60d7ca891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c7c9feb7-5098-456c-a714-689c658b49a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I</value>
      <webElementGuid>3e418824-2a84-4182-bc7c-18ccc80d722c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSFI</value>
      <webElementGuid>172f5c41-5ddb-42e8-9e6d-4514ebfcd797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>61235677-d230-4ba7-9280-e2782273d965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I-labelledby</value>
      <webElementGuid>4c35fc6b-0887-4a70-a6af-3c9affec90ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I&quot;)</value>
      <webElementGuid>df6aef18-c6f8-455b-8721-a319e64ef6e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I']</value>
      <webElementGuid>dcaed5c0-958c-45e9-9591-dd49bbf7bc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-F']/input</value>
      <webElementGuid>1500634e-d820-498c-ac00-90bb27ab06a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>66175584-00ce-43bf-924a-e246c647d5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I' and @placeholder = 'Search']</value>
      <webElementGuid>0e75039f-1d15-4c92-b839-70235a5d9804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
