<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>F4_Button</name>
   <tag></tag>
   <elementGuidId>11735fca-bea0-4c57-91f1-bd941e0f4204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpm360_managewo-manage-component---Master--idplant-vhi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='${F4_Name}']/following-sibling::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bc1f4bea-e715-4462-af52-f2310a155565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--idplant-vhi</value>
      <webElementGuid>8e1a13e2-7523-4648-b14b-8181a000a7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--idplant-vhi</value>
      <webElementGuid>4376c1fe-c12a-44b9-a071-c88eb2759a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e81d763b-5ca4-45c9-93d0-0416bb8e05a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66e41d3c-e539-4044-aaba-e1d420b7cba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>eb8fa5e6-72a7-45a1-b5af-1248d7497c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseIcon sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer</value>
      <webElementGuid>e38054d6-8d45-4b0f-99af-25a1991f5cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpm360_managewo-manage-component---Master--idplant-vhi&quot;)</value>
      <webElementGuid>5a3d2b19-3f8d-4a1c-9ae5-bf4dde5c3e83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-zpm360_managewo-manage-component---Master--idplant-vhi']</value>
      <webElementGuid>4b7a5b9f-86a5-4570-9e4f-9c98663a490c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpm360_managewo-manage-component---Master--idplant-content']/div/span</value>
      <webElementGuid>e6ad1fbb-19ea-41f0-adaa-6950580d3c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/span</value>
      <webElementGuid>22aa06a2-0dd7-4749-b126-de16ca8832da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-zpm360_managewo-manage-component---Master--idplant-vhi']</value>
      <webElementGuid>844c188e-7efc-493f-8baa-0cffff4509c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
