<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Order_ID</name>
   <tag></tag>
   <elementGuidId>88c84d77-ab6b-4b93-9dc4-ae30a94836b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__identifier6-__clone257-txt' and (text() = '908144' or . = '908144')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__identifier6-__clone257-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(text() = '${OrderID}' or . = '${OrderID}')]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1e0369e-8db0-4a6d-8833-636450e825d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__identifier6-__clone257-txt</value>
      <webElementGuid>cf54d3b6-8897-4a6b-b151-4b646411739e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__identifier6-__clone257-txt</value>
      <webElementGuid>22109b23-3f5c-4e70-939a-bdb2f1fcc93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapMTextBreakWord sapMTextMaxWidth sapUiSelectable</value>
      <webElementGuid>968e1793-45d9-4cea-a5ce-79b7ab0738ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>908144</value>
      <webElementGuid>71deb62f-94c8-4ba7-b8ed-7330a4c13452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__identifier6-__clone257-txt&quot;)</value>
      <webElementGuid>24d47b7c-52c1-4a5b-adc6-a68996e7b358</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__identifier6-__clone257-txt']</value>
      <webElementGuid>346afece-c97d-4ebf-b3ba-9836bc452b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__identifier6-__clone257-title']/span</value>
      <webElementGuid>6fef960b-fa66-4f36-a330-192e7eeb5823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::span[1]</value>
      <webElementGuid>72ed23c5-0ec7-4fe9-8bf0-f2c6065d3fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[1]/following::span[2]</value>
      <webElementGuid>07c4f873-bbca-4a89-9d43-c6e58592782c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order Created'])[1]/preceding::span[3]</value>
      <webElementGuid>c1bcf846-e97e-4d9e-b300-f11794f742ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created Date'])[1]/preceding::span[6]</value>
      <webElementGuid>9881c4eb-6a97-4abf-825a-05002843fae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='908144']/parent::*</value>
      <webElementGuid>839c3563-55a9-4145-a9f4-e8960d60f545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/span</value>
      <webElementGuid>5bcd4356-008b-49f3-ab75-f22d47c5d22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__identifier6-__clone257-txt' and (text() = '908144' or . = '908144')]</value>
      <webElementGuid>0cd5a717-b6e1-40e9-83e5-e4ca76b46fa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
