<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Order_ID</name>
   <tag></tag>
   <elementGuidId>88c84d77-ab6b-4b93-9dc4-ae30a94836b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__identifier6-__clone257-txt' and (text() = '908144' or . = '908144')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(text() = '${OrderID}')]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__identifier6-__clone257-txt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1948c563-3b6c-4606-a917-94e9843bbbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__identifier6-__clone257-txt</value>
      <webElementGuid>3414bda4-ba47-488b-8013-495d0d96005c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__identifier6-__clone257-txt</value>
      <webElementGuid>67839e2e-bf5b-4a6b-9dd5-772d12453cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapMTextBreakWord sapMTextMaxWidth sapUiSelectable</value>
      <webElementGuid>99874989-9028-4fa9-b5c3-dd66b9ff8f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>908144</value>
      <webElementGuid>7b37828e-8296-4c45-8365-28452804da3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__identifier6-__clone257-txt&quot;)</value>
      <webElementGuid>ac70f840-3d75-4cbb-be83-ceeb8f114e80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__identifier6-__clone257-txt']</value>
      <webElementGuid>d63b6272-9f8d-4829-be8b-41760d0622ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__identifier6-__clone257-title']/span</value>
      <webElementGuid>77ed0acd-6e96-4777-bac9-10a259e903c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::span[1]</value>
      <webElementGuid>0b65db63-1314-4194-a126-79c6f74d9830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[1]/following::span[2]</value>
      <webElementGuid>ec0da5ee-dd2a-4491-b9c2-ad3e73b7e00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order Created'])[1]/preceding::span[3]</value>
      <webElementGuid>d7455c96-20d7-4740-9e89-be78bd239060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created Date'])[1]/preceding::span[6]</value>
      <webElementGuid>4cf692de-b04d-46bd-8d27-84c6a879c44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='908144']/parent::*</value>
      <webElementGuid>0b5032b7-b17c-421e-ba00-cd2358746b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/span</value>
      <webElementGuid>8b9ca769-bc28-400c-a950-c2b52d34bc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__identifier6-__clone257-txt' and (text() = '908144' or . = '908144')]</value>
      <webElementGuid>27920dd9-6afb-4228-b7a8-73cb609d2a25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
