<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Plant_ID</name>
   <tag></tag>
   <elementGuidId>a4034fd5-43e8-4622-955f-b48c75a3db3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__identifier7-__clone62-txt' and (text() = 'VL01' or . = 'VL01')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(text() = '${PlantID}' or . = '${PlantID}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__identifier7-__clone62-txt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f21e4da-ea29-49fc-b05e-03bce0a0d087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__identifier7-__clone62-txt</value>
      <webElementGuid>822a7bbd-c3fe-4d3d-bc03-cbdc183ba9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__identifier7-__clone62-txt</value>
      <webElementGuid>bfbef992-2f83-4b15-bd6e-78af90225a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapMTextBreakWord sapMTextMaxWidth sapUiSelectable</value>
      <webElementGuid>640f5605-a7a1-4ac5-a131-7c493d47c4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VL01</value>
      <webElementGuid>314325a0-066a-4557-a21b-ba1fc129bd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__identifier7-__clone62-txt&quot;)</value>
      <webElementGuid>9c210cf3-aeca-47ce-ba14-68314791db15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__identifier7-__clone62-txt']</value>
      <webElementGuid>876e9bcb-1a46-4d2e-aab5-ce56544bd223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__identifier7-__clone62-title']/span</value>
      <webElementGuid>79b8570d-6b0b-4247-a6d3-fb5d337ce699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description Text'])[1]/following::span[1]</value>
      <webElementGuid>1b1d030c-473a-418e-b3e3-86571a2eadb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plant'])[1]/following::span[2]</value>
      <webElementGuid>ef48f486-a76d-4b81-8cc6-9e28bd8bbbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOB OIL REFINERY PLANT'])[1]/preceding::span[3]</value>
      <webElementGuid>d1c65d75-4576-4ec2-8cd1-9e94364fa316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[2]/preceding::span[4]</value>
      <webElementGuid>6db9944d-7fd8-4cd6-b557-0775ba5aeaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VL01']/parent::*</value>
      <webElementGuid>e231781e-042e-43dd-9650-c0bac03f7e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/span</value>
      <webElementGuid>4a96e32d-ed15-4505-91c2-6572475465e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__identifier7-__clone62-txt' and (text() = 'VL01' or . = 'VL01')]</value>
      <webElementGuid>e8ae59b4-cc0f-4106-8345-21f6e8358727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
