<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pop_Up_Button</name>
   <tag></tag>
   <elementGuidId>0d8c9318-c932-43be-9349-6fe8ff41c064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__identifier6-__clone257-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[text() = '${PopName}' ]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__identifier6-__clone257-txt' and (text() = '908144' or . = '908144')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>22c55f2e-05ad-4673-99a8-25572dcdea5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__identifier6-__clone257-txt</value>
      <webElementGuid>af23d9df-e3a6-4012-976c-c95b9ca1e640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__identifier6-__clone257-txt</value>
      <webElementGuid>c977f41f-56a3-489a-8d83-b1a4b74fbce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapMTextBreakWord sapMTextMaxWidth sapUiSelectable</value>
      <webElementGuid>63873b8a-8fd2-41f4-86ff-9a0c32aa6159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>908144</value>
      <webElementGuid>3ded18d3-3a4e-4e7e-894d-e87a001e4753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__identifier6-__clone257-txt&quot;)</value>
      <webElementGuid>9a2d2b47-2990-4f0e-8fc9-6e9a6d6ee52e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__identifier6-__clone257-txt']</value>
      <webElementGuid>a05eaf96-0547-4a32-b095-e38c3dae6408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__identifier6-__clone257-title']/span</value>
      <webElementGuid>177fa13c-3cb8-4d30-acf6-a6802d1de2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::span[1]</value>
      <webElementGuid>70ec1522-a6b7-4da7-9ff4-b68add0cc144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[1]/following::span[2]</value>
      <webElementGuid>97d8e48c-03ce-450a-a79e-869d34b4fdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order Created'])[1]/preceding::span[3]</value>
      <webElementGuid>6f91e172-4e0f-4216-b28e-a0fa5c5b92f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created Date'])[1]/preceding::span[6]</value>
      <webElementGuid>8ae63b8a-7582-4090-9ccd-6d4fc5fdfe93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='908144']/parent::*</value>
      <webElementGuid>957a8e1c-1653-4f02-b4ff-88d91b91b13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/span</value>
      <webElementGuid>c5b85eb7-7dfe-4180-9aa0-efd7b0f2a82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__identifier6-__clone257-txt' and (text() = '908144' or . = '908144')]</value>
      <webElementGuid>662619b2-e17c-4592-a858-afca61afb759</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
