<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_Box_Reset_Button</name>
   <tag></tag>
   <elementGuidId>3b2d4daa-6d63-4816-97b6-9e9fb43ed5c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__item4-application-zpm360_managewo-manage-component---Master--idplant-0_cell0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@title = 'Reset']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>aca0cf57-9e27-4f15-9ef5-83c798af958b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__item4-application-zpm360_managewo-manage-component---Master--idplant-0_cell0</value>
      <webElementGuid>c18a9945-97df-4818-b68c-487a72466390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-column</name>
      <type>Main</type>
      <value>__column0</value>
      <webElementGuid>88d3c354-e956-412a-b669-7945f54c3e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>__label0</value>
      <webElementGuid>e438cfe3-9acc-4022-bbd6-bed226fc5948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMListTblCell</value>
      <webElementGuid>f9c7f698-764c-44f0-b549-ecc44ea9b79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PL01Object Identifier</value>
      <webElementGuid>7fcc2a01-8f9d-49bd-8aad-c4a805f653de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item4-application-zpm360_managewo-manage-component---Master--idplant-0_cell0&quot;)</value>
      <webElementGuid>2a01b83c-6b17-4e59-a798-97724f74551f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='__item4-application-zpm360_managewo-manage-component---Master--idplant-0_cell0']</value>
      <webElementGuid>bf4090d0-6021-410f-9c9b-7e0a93846406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='__item4-application-zpm360_managewo-manage-component---Master--idplant-0']/td[2]</value>
      <webElementGuid>ee2575d3-5689-4574-8a6e-d3f83f3e9974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plant Description'])[1]/following::td[2]</value>
      <webElementGuid>92d18b16-7116-4ce0-b7e4-f95446e95606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plant'])[1]/following::td[2]</value>
      <webElementGuid>f935d5d1-8aed-465b-aabc-694899cc43c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pittsburgh Plant'])[1]/preceding::td[1]</value>
      <webElementGuid>5992a627-abc9-460c-9378-bc9bc3e19799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>293ff929-2a51-4abe-8ddf-6fda22d2f6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = '__item4-application-zpm360_managewo-manage-component---Master--idplant-0_cell0' and (text() = 'PL01Object Identifier' or . = 'PL01Object Identifier')]</value>
      <webElementGuid>3d27bff8-29d3-409a-b1a1-1df96ab8835a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
