<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_Box_Input</name>
   <tag></tag>
   <elementGuidId>440e2545-9bee-4ba5-b64d-c087eccb2842</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'search' and @id = 'application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I' and @placeholder = 'Search']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73bb7caa-cb28-4968-aca7-0a64e91a78f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c183c58b-9475-4442-9557-57e91e6e6b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b17b0888-6c3b-4378-90fd-48d3f279bc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I</value>
      <webElementGuid>3a37517e-313a-414a-85e7-831ffec61634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSFI</value>
      <webElementGuid>e4fd7d14-7055-4b74-ae0a-f94e35fd8cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>e4a8523b-6e4f-43e7-b423-4ac39712089b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I-labelledby</value>
      <webElementGuid>ca6f9934-a10a-46a1-8867-078ffda023e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I&quot;)</value>
      <webElementGuid>6eb33a2d-b2b4-4f50-807d-28c93a3736cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I']</value>
      <webElementGuid>75befd1c-50e3-4aec-9f34-d3bd1853fa8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-F']/input</value>
      <webElementGuid>9ae98156-112d-4b6e-9d8a-fd161dd27935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>73b1fda0-86d4-43aa-8a47-24707a78867a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'application-zpm360_managewo-manage-component---Master--smartFilterBar-btnBasicSearch-I' and @placeholder = 'Search']</value>
      <webElementGuid>eb92bf91-2216-48f1-881f-570249b94ee1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
