<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select _Any_ Criteria</name>
   <tag></tag>
   <elementGuidId>01cba114-bebc-469d-9d16-d2dccf0ba2f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Please Select Any Search Criteria' or . = 'Please Select Any Search Criteria')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sap-ui-static']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sapMMessageToast.sapUiSelectable.sapContrast.sapContrastPlus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c5d2a0f-43d6-44b5-b9c7-8f88957716ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMMessageToast sapUiSelectable sapContrast sapContrastPlus</value>
      <webElementGuid>a1948fc3-6b5c-492b-bded-ae7472c85e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>b2ef764f-896b-4dea-aa4e-c56a96935e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-popup</name>
      <type>Main</type>
      <value>id-1651760615800-256</value>
      <webElementGuid>2219084d-8ff0-4e29-a8ae-a1dbd73bbb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select Any Search Criteria</value>
      <webElementGuid>52730874-dd0d-4c19-8dc9-73428797ef72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sap-ui-static&quot;)/div[@class=&quot;sapMMessageToast sapUiSelectable sapContrast sapContrastPlus&quot;]</value>
      <webElementGuid>e826f107-a405-4d80-b4a1-1b5394634fe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sap-ui-static']/div[2]</value>
      <webElementGuid>ac5dd1e3-ac14-4838-a9bd-714ecd572d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[1]</value>
      <webElementGuid>a95f128a-ed73-4a06-ba2a-2b275052001c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[3]</value>
      <webElementGuid>5b5ea2d3-69f8-4c19-a787-6a0163469e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please Select Any Search Criteria']/parent::*</value>
      <webElementGuid>51ee195c-a9c6-48e5-89fd-f17994610da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>767748ab-3aad-4c23-8725-c4cf8ed26027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Please Select Any Search Criteria' or . = 'Please Select Any Search Criteria')]</value>
      <webElementGuid>1cf7ac6a-d022-4eda-8ef1-5126a597bfef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
