<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>System_Status</name>
   <tag></tag>
   <elementGuidId>86f5913b-3b34-4c8e-90d5-fc9ab8b2a052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__button17-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(text() = '${sys_Status}')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__button17-BDI-content' and (text() = 'TECO' or . = 'TECO')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>33e817fe-f891-4dce-abfb-514329b71db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__button17-BDI-content</value>
      <webElementGuid>71728e2f-1720-43ae-bc58-dbe7b51f7ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TECO</value>
      <webElementGuid>bbc9b0db-fda9-4985-a3cc-da8513f776ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__button17-BDI-content&quot;)</value>
      <webElementGuid>ef131a3b-57e0-45e0-95a5-9b298aae70d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='__button17-BDI-content']</value>
      <webElementGuid>be386669-2862-4b91-a95c-0761212e9844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__button17-content']/bdi</value>
      <webElementGuid>f83664d9-4996-49df-a950-c4f214e90490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time based plan for Equipment'])[2]/following::bdi[1]</value>
      <webElementGuid>9f8a625a-5528-47ee-9dd3-ca49fefd4825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[3]/following::bdi[1]</value>
      <webElementGuid>9eef3361-a4f5-4291-aa05-e96bdd7c2cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Type:'])[1]/preceding::bdi[1]</value>
      <webElementGuid>20581896-8506-42b2-881e-1bec17ac2350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OL03 Preventive Maintenance'])[1]/preceding::bdi[1]</value>
      <webElementGuid>f6657d9c-686d-400d-b64e-85eea296275a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TECO']/parent::*</value>
      <webElementGuid>3a90df82-a1cc-411e-8e58-33f1c2e64de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/span/span/bdi</value>
      <webElementGuid>fa4ce01c-c24e-4cda-ae02-7fe5b04ec3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = '__button17-BDI-content' and (text() = 'TECO' or . = 'TECO')]</value>
      <webElementGuid>0d18e7ff-efed-47cd-af2a-aa0ffe9c6441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
