<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table_Data_Display_Field_Index</name>
   <tag></tag>
   <elementGuidId>ebf9f0ec-16aa-4aee-b0af-0a760ceeb571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>((//table[contains(@id,'${tableName}')])//tr[${row}]//td[${col}]//span)[${srow}]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8764c97f-8108-461a-9ca7-243de2c35a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg</value>
      <webElementGuid>04867558-ef1f-4eb0-8e11-c31b10300562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMCbActiveStateOff sapMCbBg sapMCbHoverable sapMCbMark</value>
      <webElementGuid>d7a4611d-9c5f-487b-bcee-45eca529313d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg&quot;)</value>
      <webElementGuid>301002b0-0931-487e-8cba-d3d1f464fd35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg']</value>
      <webElementGuid>7df6b297-4fd7-45bb-aeff-061057a15584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpm360_managewo-manage-component---Master--idTable2-sa']/div</value>
      <webElementGuid>d23d7491-d041-478e-9645-c0e8bb06140f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard'])[2]/following::div[8]</value>
      <webElementGuid>4c20ac59-920e-4a5d-b08a-fb74785f48c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order (61)'])[1]/following::div[13]</value>
      <webElementGuid>ff21525d-6ad2-4fc3-ad1c-88044632bed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[1]/preceding::div[1]</value>
      <webElementGuid>df9b8ef8-9bb6-49c4-9117-371708076b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::div[2]</value>
      <webElementGuid>f6b3a423-83a8-4d23-9ff8-a4bb3f0f4a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/div/div</value>
      <webElementGuid>014cfef0-10ea-4667-b44f-d8b62463ee3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg']</value>
      <webElementGuid>3f153738-8743-45a4-acad-39df276cd03b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
