<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table_Data</name>
   <tag></tag>
   <elementGuidId>1475a7a2-d241-4a9a-848d-ced76cfec04a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//table[contains(@id,'${tableName}')])//tr[${row}]//td[${col}]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d08c832-bb25-42f0-9f3a-86b0c68e698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg</value>
      <webElementGuid>8f839671-bfd6-4607-bce1-49b289c29bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMCbActiveStateOff sapMCbBg sapMCbHoverable sapMCbMark</value>
      <webElementGuid>f32ca1e8-f756-40ad-a441-de098dd7aed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg&quot;)</value>
      <webElementGuid>e8781e5a-9fb7-4740-b3a8-717db900993a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg']</value>
      <webElementGuid>b9048724-8348-4c28-aa1e-3a00a6fab12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpm360_managewo-manage-component---Master--idTable2-sa']/div</value>
      <webElementGuid>1a7a1fd3-121c-4931-a0be-d23d57c9f08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard'])[2]/following::div[8]</value>
      <webElementGuid>2f482c4f-6760-4b0e-979f-4c74f885b6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order (61)'])[1]/following::div[13]</value>
      <webElementGuid>f95d1b84-ac97-43ca-9e45-d0628e549d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[1]/preceding::div[1]</value>
      <webElementGuid>b9d0c6e7-615d-443c-bff8-768039abfe74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::div[2]</value>
      <webElementGuid>a3a60aad-a8d7-48c5-b571-0d091b4b13fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/div/div</value>
      <webElementGuid>6434c021-9dfc-463f-bd65-4b762f6017bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'application-zpm360_managewo-manage-component---Master--idTable2-sa-CbBg']</value>
      <webElementGuid>b227aa4f-20e4-4207-b8d2-24fef8196fb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
