<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tabs</name>
   <tag></tag>
   <elementGuidId>06213d0f-cf6e-4cb7-b0e7-695c68720778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//bdi[(text() = '${Tab}')])
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__identifier6-__clone257-txt' and (text() = '908144' or . = '908144')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__identifier6-__clone257-txt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>08e938ef-6477-4d06-aef1-fd61298e2739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__identifier6-__clone257-txt</value>
      <webElementGuid>525f7181-b1b8-4efc-9694-9e6947a04674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__identifier6-__clone257-txt</value>
      <webElementGuid>0a6e73b4-e165-4d5c-b932-28b93ca27461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapMTextBreakWord sapMTextMaxWidth sapUiSelectable</value>
      <webElementGuid>3d07c92b-f1e0-4f30-8596-fa9f77eff89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>908144</value>
      <webElementGuid>d410a957-7c3f-4627-8f54-2d54b4fa6a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__identifier6-__clone257-txt&quot;)</value>
      <webElementGuid>68883ef3-2948-4f8e-a5ec-8aa1432dac86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__identifier6-__clone257-txt']</value>
      <webElementGuid>499c3763-f425-47b7-a8cb-e4e59b15f271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__identifier6-__clone257-title']/span</value>
      <webElementGuid>870551a2-aa72-4801-b70f-1c005fa38dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::span[1]</value>
      <webElementGuid>27f81fd1-47bf-4b33-a414-415f85ebab86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[1]/following::span[2]</value>
      <webElementGuid>c902c1f3-e451-4e76-88cf-81458fd502c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order Created'])[1]/preceding::span[3]</value>
      <webElementGuid>dbe6df84-8547-4ca4-8df3-8de386a08723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created Date'])[1]/preceding::span[6]</value>
      <webElementGuid>0952cfe4-4cf9-45fc-96ce-cac1f9a19e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='908144']/parent::*</value>
      <webElementGuid>b631dc09-2892-46c3-baf8-b34ebbc7a3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/span</value>
      <webElementGuid>bc526c16-be70-41ea-ac76-11a94611ff15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__identifier6-__clone257-txt' and (text() = '908144' or . = '908144')]</value>
      <webElementGuid>779f6e1a-8ddd-44ef-9246-e13c55b935db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
