<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tabs_Index</name>
   <tag></tag>
   <elementGuidId>4ce7d2f3-aa54-414d-aab4-56c2021aa2cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[(text() = '${Tab}')])['${index}']
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '__identifier6-__clone257-txt' and (text() = '908144' or . = '908144')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__identifier6-__clone257-txt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>daf65751-e669-4bb8-aca8-c2d3b867d443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__identifier6-__clone257-txt</value>
      <webElementGuid>9f265490-465f-4762-b6db-70269b8e55e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__identifier6-__clone257-txt</value>
      <webElementGuid>64d293fc-f708-4b43-a0e2-bac9ddee5781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapMTextBreakWord sapMTextMaxWidth sapUiSelectable</value>
      <webElementGuid>00625219-6271-468c-9e5e-faaace83d5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>908144</value>
      <webElementGuid>f5b54c0e-5fb4-40a1-a41c-be2f77e57f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__identifier6-__clone257-txt&quot;)</value>
      <webElementGuid>ba4b500c-e45d-441c-a59e-ae955404b73c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__identifier6-__clone257-txt']</value>
      <webElementGuid>7e695f5a-41cd-4c94-bc11-d3bb8edee041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__identifier6-__clone257-title']/span</value>
      <webElementGuid>5b8e8e63-84e7-45d4-83eb-a046e84d01eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::span[1]</value>
      <webElementGuid>2b5467fc-788c-42a3-aeee-07b7352c0255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[1]/following::span[2]</value>
      <webElementGuid>334a9148-ccd2-4876-bc4c-b3bf6cd25ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order Created'])[1]/preceding::span[3]</value>
      <webElementGuid>2116c778-ef66-44dd-862d-22d2aa14903c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created Date'])[1]/preceding::span[6]</value>
      <webElementGuid>766c14fc-89e6-46b5-888e-6bd15df98dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='908144']/parent::*</value>
      <webElementGuid>e885bb35-bf19-4550-9f6b-8e1633583b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/span</value>
      <webElementGuid>06f74c5e-e406-4aab-a977-8c5da5deb013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__identifier6-__clone257-txt' and (text() = '908144' or . = '908144')]</value>
      <webElementGuid>b44846d5-d4f8-44c5-a289-b3a164e3f53a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
