<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_location (B-MOB-PAPB)_technical--treeta_b64d5f</name>
   <tag></tag>
   <elementGuidId>c9a8c59b-6f44-4f8a-8dd4-8f1a251fb7c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#technical--treetable1-technical--Tree1-2-selectSingle-Button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'technical--treetable1-technical--Tree1-2-selectSingle-Button']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='technical--treetable1-technical--Tree1-2-selectSingle-Button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59144e7c-f36d-417f-a961-54a596fbfda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>technical--treetable1-technical--Tree1-2-selectSingle-Button</value>
      <webElementGuid>c0a1b5cb-553a-45c8-ac50-ce86b63b6792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMRbBOut sapMRbHoverable</value>
      <webElementGuid>a6a14d2c-e8b8-4cf6-b5eb-6c3c33a46862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;technical--treetable1-technical--Tree1-2-selectSingle-Button&quot;)</value>
      <webElementGuid>26786282-ef4c-43c6-816d-11a785e7079e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='technical--treetable1-technical--Tree1-2-selectSingle-Button']</value>
      <webElementGuid>f8d12728-fe6c-47e1-bdbd-6928d2e7f166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='technical--treetable1-technical--Tree1-2-selectSingle']/div/div</value>
      <webElementGuid>f68e0045-a462-4d87-b0a5-14abcdefeb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='location (B-MOB-PAPB)'])[1]/following::div[3]</value>
      <webElementGuid>db2e785d-e2b6-4af3-98e3-dc684c116c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company MOB (B-MOB)'])[1]/following::div[8]</value>
      <webElementGuid>a87ca16c-ce97-4b3f-a453-c2e0cfc5700c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='stacker (10017302)'])[1]/preceding::div[2]</value>
      <webElementGuid>f142de9f-c91e-4b7a-a21e-625754f6ce2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SS chamber Equipment (10017303)'])[1]/preceding::div[7]</value>
      <webElementGuid>741be37e-ffde-4aa3-9079-8a4ec7929f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div</value>
      <webElementGuid>e2b66940-dbcb-450f-a73b-c04e6913d63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'technical--treetable1-technical--Tree1-2-selectSingle-Button']</value>
      <webElementGuid>e44dfe3b-0da5-4a04-af91-690b77c7da69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
