<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ok</name>
   <tag></tag>
   <elementGuidId>bbbd66b9-7cff-4f18-bf4e-c2ad409ab6ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__button15-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__button15-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5547f4f4-8f33-4cf7-891d-1fbf66380724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__button15-inner</value>
      <webElementGuid>a9340575-d659-4ab4-8b22-7e9ed47db7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnEmphasized sapMBtnHoverable sapMBtnInner sapMBtnText sapMFocusable</value>
      <webElementGuid>3b7fa0a1-ef0c-4529-8cf5-2daf32253d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>b1d935a8-fd04-41c7-b495-e7e6818a81ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__button15-inner&quot;)</value>
      <webElementGuid>fac5b957-dbc7-4860-b3ee-2f0d6b16b3e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__button15-inner']</value>
      <webElementGuid>7c5d79d2-5301-4cec-96f6-647bb950c5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='__button15']/span</value>
      <webElementGuid>f14ccea2-56ae-42f9-a450-aa23838f9f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='plant (B-MOB-PAPB-CDU)'])[1]/following::span[1]</value>
      <webElementGuid>454dccb9-33fa-43db-b966-fe76d3233f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motor (10017305)'])[1]/following::span[4]</value>
      <webElementGuid>5a95335c-7e0f-4b21-8646-7e52aedac48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B Company'])[1]/preceding::span[7]</value>
      <webElementGuid>eb71651a-4417-45bc-89a4-3c3f4c05baaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/button/span</value>
      <webElementGuid>9f33530b-56d3-4e90-b07a-7e999cfc3fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__button15-inner' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>a93b51ce-2c4f-4dbf-9981-874acef1d8f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
