<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Company MOB (B-MOB)_technical--treetab_5fcc14</name>
   <tag></tag>
   <elementGuidId>d2879332-49f9-4963-b5af-7287f081d5b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#technical--treetable1-technical--Tree1-1-expander</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='technical--treetable1-technical--Tree1-1-expander']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b41a7b5-c349-472b-a3d6-eed3c72accf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>technical--treetable1-technical--Tree1-1-expander</value>
      <webElementGuid>c74d4a68-8eaf-42b1-bc37-b8d8f85b1292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>technical--treetable1-technical--Tree1-1-expander</value>
      <webElementGuid>ff7181dd-4c2d-4ead-a315-1676624d9531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>571edc8d-e047-4282-adfd-6d92fffa6f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc2e21e7-ad58-4f83-a1c9-646322d0b61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8a15c680-3a76-4996-9f1b-0ae0f04c12a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTreeItemBaseExpander sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer</value>
      <webElementGuid>f3b11461-7e07-46e8-b1bd-fd9421d49b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;technical--treetable1-technical--Tree1-1-expander&quot;)</value>
      <webElementGuid>9b12abb9-9aef-4a45-85af-7f4a487cf7d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='technical--treetable1-technical--Tree1-1-expander']</value>
      <webElementGuid>041e6853-62b8-4c17-a1fe-f154e5863aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='technical--treetable1-technical--Tree1-1']/span</value>
      <webElementGuid>928b8fa9-d8ce-482b-bbac-39cdc051c9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>87283d6f-c743-4f93-b099-efcb1915897e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'technical--treetable1-technical--Tree1-1-expander']</value>
      <webElementGuid>8a12adf3-422f-4499-a458-f7ae36f4feb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
